#!/bin/bash
set -e

USER_LOGIN="vnc"
USER_PASSWORD="${USER_PASSWORD:-vncpass}"
USER_HOME="/home/${USER_LOGIN}"
USER_DATA_DIR="${USER_HOME}/data"
VNC_PORT="${VNC_PORT:-5901}"
VNC_DISPLAY="1"
VNC_DEPTH="24"
VNC_GEOMETRY="1280x720"
VNC_OPTIONS=${VNC_OPTIONS:-"-depth ${VNC_DEPTH} -geometry ${VNC_GEOMETRY} :${VNC_DISPLAY} -rfbport ${VNC_PORT}"}

appInit () {
  echo 'Init ...'
  echo "${USER_LOGIN}:${USER_PASSWORD}" | chpasswd
  chown -R vnc:vnc ${USER_HOME}/share
  su ${USER_LOGIN} -c "touch ${USER_HOME}/.Xresources"
  su ${USER_LOGIN} -c "touch ${USER_HOME}/.Xauthority"
  su ${USER_LOGIN} -c "mkdir -p ${USER_HOME}/.vnc"
  su ${USER_LOGIN} -c "echo "${USER_PASSWORD}" | vncpasswd -f > ${USER_HOME}/.vnc/passwd"
  su ${USER_LOGIN} -c "chmod 600 ${USER_HOME}/.vnc/passwd"
}

appStart () {
  appInit

  echo 'Start ...'
  /etc/init.d/ssh start
  su ${USER_LOGIN} -c "vncserver ${VNC_OPTIONS} && tail -F ${USER_HOME}/.vnc/*.log"
}

appHelp () {
  echo "Available options:"
  echo " start          - Starts the gitlab server (default)"
  echo " init           - Initialize the ubuntu desktop but don't start it."
  echo " help           - Displays the help"
  echo " [command]      - Execute the specified linux command eg. bash."
}

case "$1" in
  start)
    appStart
    ;;
  init)
    appInit
    ;;
  help)
    appHelp
    ;;
  *)
    if [ -x $1 ]; then 
      $1
    else
      prog=$(which $1)
      if [ -n "${prog}" ] ; then
        shift 1
        $prog $@
      else
        appHelp
      fi
    fi
    ;;
esac

exit 0
